import { useEffect, useRef } from 'react';
import { gsap } from 'gsap';
import { asset } from '../assets';

const stories = [
  { image: '57a23.png', label: 'STRESS RECOVERY', title: 'A Journey from stress to serenity', description: 'After months of feeling overwhelmed by work and daily responsibilities, Saqib Mahmud embraced a personalized recovery plan that helped him develop healthier routines, enjoy better sleep, and reconnect with his emotional well-being.', quote: '“The support, peaceful environment, and personalized guidance gave me the confidence to prioritize my well-being again.”', name: 'Saqib Mahmud' },
  { image: 'c015c.png', label: 'MINDFULNESS', title: 'A return to a calmer rhythm', description: 'With gentle practices and regular support, Maya rebuilt a daily rhythm that made space for quiet focus, steadier energy, and meaningful moments of rest.', quote: '“I learned how to slow down, listen to myself, and make calm part of every day.”', name: 'Maya L.' },
  { image: 'd456c.png', label: 'PERSONAL GROWTH', title: 'Finding confidence in every step', description: 'A focused plan helped Nina turn uncertainty into forward movement, with practical tools that supported confidence at home, work, and beyond.', quote: '“The small changes added up. I feel more grounded and confident in my choices.”', name: 'Nina R.' },
];
function StoryCard({ story, index, cardRef }: { story: typeof stories[number]; index: number; cardRef: (node: HTMLDivElement | null) => void }) { return <article className="story-card" ref={cardRef}><div className="story-photo"><img src={asset(story.image)} alt="" /><div className="quote"><div className="stars">{Array.from({ length: 5 }, (_, star) => <img src={asset('44c8f.svg')} alt="" key={star} />)}</div><blockquote>{story.quote}</blockquote><p><strong>{story.name}</strong> · New York, USA</p></div></div><div className="story-copy"><span className="badge">{story.label}</span><h3>{story.title}</h3><p>{story.description}</p><a className="pill" href={`#story-benefits-${index + 1}`}>View Details<span className="arrow"><img src={asset('745f4.svg')} alt="" /></span></a><div className="benefits" id={`story-benefits-${index + 1}`}><p><span><img src={asset('8cb78.svg')} alt="" /></span>Experience Deeper, More Restorative Sleep Every Night.</p><p><span><img src={asset('ed0b4.svg')} alt="" /></span>Follow a Personalized 8-Week Wellness & Recovery Program.</p><p><span><img src={asset('fa96c.svg')} alt="" /></span>Build Healthier Habits for a Calmer, More Balanced Everyday Life.</p></div></div></article>; }
export function Stories() {
  const deck = useRef<HTMLDivElement>(null); const pin = useRef<HTMLDivElement>(null); const cards = useRef<(HTMLDivElement | null)[]>([]);
  useEffect(() => { const target = deck.current, sticky = pin.current; if (!target || !sticky || window.innerWidth < 801 || window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; let frame = 0; const update = () => { frame = 0; const top = target.getBoundingClientRect().top + window.scrollY; const stickyTop = Math.max(24, window.innerHeight - sticky.offsetHeight); const progress = Math.max(0, Math.min(1, (window.scrollY - (top - stickyTop)) / Math.max(1, target.offsetHeight - sticky.offsetHeight))); const second = Math.max(0, Math.min(1, (progress - .01) / .42)); const third = Math.max(0, Math.min(1, (progress - .51) / .42)); if (cards.current[1]) gsap.set(cards.current[1], { clipPath: `inset(${100 - second * 100}% 0 0 0)` }); if (cards.current[2]) gsap.set(cards.current[2], { clipPath: `inset(${100 - third * 100}% 0 0 0)` }); }; const request = () => { if (!frame) frame = requestAnimationFrame(update); }; window.addEventListener('scroll', request, { passive: true }); window.addEventListener('resize', request); request(); return () => { cancelAnimationFrame(frame); window.removeEventListener('scroll', request); window.removeEventListener('resize', request); }; }, []);
  return <section className="stories section" id="stories"><div className="stories-stack-heading"><span className="badge">CLIENT JOURNEY</span><h2>Real stories of growth, healing,<br /> and lasting change.</h2></div><div className="story-deck" ref={deck}><div className="story-stack-pin" ref={pin}>{stories.map((story, index) => <StoryCard key={story.label} story={story} index={index} cardRef={node => { cards.current[index] = node; }} />)}</div></div></section>;
}
