import { useEffect, useRef, useState } from 'react';
import { SilkBackground } from './hero-scene';

const photoSet = [
  'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=600&q=85',
  'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=85',
  'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=85',
  'https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=600&q=85',
  'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=600&q=85',
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=85',
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=600&q=85',
];
const journeyCards = [
  ['Your journey to feeling better starts here', 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=1200&q=85', 'col-span-2'],
  ['Personalized guidance for your unique needs', null, ''],
  ['Build a calmer, more balanced life', null, ''],
  ['Support that meets you where you are', 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=85', 'col-span-2'],
];
const services = ['Individual therapy', 'Stress & anxiety support', 'Couples & family care', 'Yoga & mentoring', 'Mindfulness practice', 'Personal growth coaching'];

function Pill({ children, light = false }) {
  return <span className={`inline-flex items-center gap-3 rounded-full px-5 py-3 text-sm font-bold ${light ? 'bg-white text-stone-900' : 'bg-[#e8e0d9] text-stone-900'}`}>{children}<span className="grid h-8 w-8 place-items-center rounded-full bg-[#dfb57d] text-lg leading-none">›</span></span>;
}

function Header() {
  const [open, setOpen] = useState(false);
  return <header className="absolute inset-x-0 top-0 z-20 flex items-center justify-between px-6 py-7 text-white md:px-13 md:py-10">
    <a href="#home" className="font-serif text-5xl tracking-[-0.08em] md:text-6xl">Parna</a>
    <button onClick={() => setOpen(!open)} className="grid h-10 w-10 place-items-center text-3xl" aria-label="Open navigation">☰</button>
    {open && <nav className="absolute right-6 top-22 w-56 rounded-2xl border border-white/20 bg-[#472c06]/95 p-4 shadow-2xl md:right-13"><a className="block rounded-lg px-3 py-2 hover:bg-white/10" href="#about">About</a><a className="block rounded-lg px-3 py-2 hover:bg-white/10" href="#how">How it works</a><a className="block rounded-lg px-3 py-2 hover:bg-white/10" href="#services">Services</a></nav>}
  </header>;
}

function Hero() {
  return <section id="home" className="relative isolate min-h-[850px] overflow-hidden bg-[#4c3004] text-white md:min-h-[982px]">
    <div className="absolute inset-0 -z-10"><SilkBackground /></div><Header />
    <div className="relative z-10 mx-auto flex min-h-[850px] max-w-[1512px] items-center px-6 pt-28 pb-14 md:min-h-[982px] md:px-13">
      <div className="max-w-3xl"><h1 className="font-serif text-5xl leading-[1.05] tracking-tight md:text-7xl">TRANSFORM YOUR <em className="font-serif text-[#fff6de]">Life</em><br />INTO A WILDLY <em className="font-serif text-[#fff6de]">Abundant</em><br />JOURNEY</h1>
        <p className="mt-5 max-w-2xl text-base font-medium leading-relaxed md:text-lg">Empowering designers, illustrators, and artists to craft sustainable, purpose-driven businesses that bring freedom.</p>
        <a href="#how" className="mt-8 inline-block rounded-full bg-white/15 px-7 py-4 text-sm font-bold backdrop-blur">START YOUR JOURNEY →</a>
        <div className="mt-12 max-w-xl rounded-3xl bg-white/15 p-6 backdrop-blur-md"><h2 className="text-3xl font-semibold">How are you feeling today?</h2><div className="mt-8 flex flex-wrap gap-4">{Array.from({ length: 5 }, (_, i) => <button key={i} className="rounded-full border border-white px-4 py-2 text-sm text-white/85">＋ Constant Stress</button>)}</div></div>
      </div>
    </div>
  </section>;
}

function AboutArc() {
  const rail = useRef();
  useEffect(() => {
    let frame; const started = performance.now(); const cards = [...rail.current.children];
    const place = now => { const compact = innerWidth < 768; const r = compact ? 320 : 945; const cy = compact ? 430 : 1161; cards.forEach((card, i) => { const phase = (i / cards.length + (now - started) / 34000) % 1; const degree = 180 + phase * 180; const rad = degree * Math.PI / 180; card.style.left = `${rail.current.clientWidth / 2 + r * Math.cos(rad)}px`; card.style.top = `${cy + r * Math.sin(rad)}px`; card.style.transform = `translate(-50%, -50%) rotate(${degree - 270}deg)`; }); frame = requestAnimationFrame(place); };
    frame = requestAnimationFrame(place); return () => cancelAnimationFrame(frame);
  }, []);
  return <><div ref={rail} className="pointer-events-none absolute inset-x-0 top-0 h-[1000px] overflow-visible">{Array.from({ length: 10 }, (_, i) => <img key={i} src={photoSet[i % photoSet.length]} className="absolute h-[116px] w-[100px] rounded-2xl object-cover shadow-xl md:h-[230px] md:w-[200px]" alt="" />)}</div>
    <div className="pointer-events-none absolute left-1/2 top-[421px] hidden h-0 w-0 md:block">{Array.from({ length: 91 }, (_, i) => { const angle = (202.5 + i * 1.5) * Math.PI / 180; return <i key={i} className="absolute h-0.5 w-3 bg-stone-950" style={{ left: `${Math.cos(angle) * 790}px`, top: `${Math.sin(angle) * 790 + 740}px`, transform: `rotate(${i * 1.5 + 22.5}deg)` }} />; })}</div>
  </>;
}

function About() {
  return <><section id="about" className="relative overflow-hidden bg-white pt-0"><AboutArc />
    <div className="pointer-events-none absolute left-1/2 top-[205px] h-[235px] w-full -translate-x-1/2 overflow-hidden md:hidden"><div className="absolute left-1/2 top-0 h-[410px] w-[660px] -translate-x-1/2 rounded-[50%] border-2 border-dashed border-stone-700" /></div>
    <div className="relative z-10 mx-auto max-w-4xl px-6 pt-[340px] pb-10 text-center md:pt-[474px] md:pb-12"><span className="rounded-full border border-stone-200 px-3 py-2 text-[10px] font-bold tracking-[0.14em] text-stone-500">WHAT PEOPLE</span><h2 className="mt-5 font-serif text-5xl leading-none text-stone-900 md:text-6xl">Helping people find calm, clarity,<br className="hidden md:block" /> and confidence</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-relaxed text-stone-500 md:text-base">We believe meaningful care starts with listening. Our goal is to help our clients succeed despite stress, anxiety, and life changes.</p><a href="#how" className="mt-6 inline-block"><Pill>Learn More</Pill></a></div>
  </section><section className="bg-white px-6 pb-18"><div className="mx-auto grid max-w-5xl grid-cols-2 divide-x divide-y border-y border-stone-200 md:grid-cols-4 md:divide-y-0"><Metric value="12+" label="Years of Experience" /><Metric value="25+" label="Wellness Programs" /><Metric value="98%" label="Client Satisfaction" /><Metric value="1:1" label="Personalized Support" /></div></section></>;
}

function Metric({ value, label }) { return <div className="p-5 text-center"><strong className="text-4xl">{value}</strong><span className="mt-2 block text-sm text-stone-500">{label}</span></div>; }

function HowItWorks() { return <section id="how" className="mx-auto max-w-5xl px-6 py-20 md:py-28"><div className="mx-auto mb-10 max-w-xl text-center"><h2 className="mt-5 font-serif text-5xl leading-none">Your journey to feeling<br /> better starts here</h2></div><div className="grid gap-4 md:grid-cols-2">{journeyCards.map(([title, image], i) => <article key={`${title}-${i}`} className="relative min-h-[260px] overflow-hidden rounded-2xl border border-amber-300 bg-[#f6dfb9] p-7 md:min-h-[330px]"><h3 className={`absolute bottom-7 z-10 max-w-xs font-serif text-3xl leading-[.92] ${image ? 'text-white' : 'text-stone-900'}`}>{title}</h3>{image && <img className="absolute inset-0 h-full w-full object-cover" src={image} alt="" />}{image && <div className="absolute inset-0 bg-black/25" />}</article>)}</div></section>; }

function Services() { const tags = [['1-ON-1 SESSIONS', 'STRESS MANAGEMENT'], ['STRESS MANAGEMENT', 'MINDFULNESS'], ['1-ON-1 SESSIONS', 'RELATIONSHIP GUIDANCE'], ['YOGA SESSIONS', 'PERSONALIZED SUPPORT'], ['MINDFULNESS', 'BREATHWORK'], ['COACHING SESSIONS', 'MINDFULNESS']]; return <section id="services" className="mx-auto max-w-7xl px-6 py-20"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><span className="rounded-full bg-[#e8e0d9] px-3 py-2 text-[10px] font-bold tracking-[0.12em]">WHY CHOOSE PARNA</span><h2 className="mt-5 max-w-xl font-serif text-5xl leading-none">Support for every step of your wellness journey</h2></div><p className="max-w-xs text-sm leading-relaxed text-stone-500">Personalized care and practical guidance to help you navigate challenges and create lasting positive change.</p></div><div className="mt-10 grid gap-9 md:grid-cols-[1.55fr_.45fr]"><div className="border-y border-stone-200">{services.map((service, i) => <div key={service} className="flex flex-wrap items-center gap-3 border-b border-stone-200 py-4 last:border-0"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#e8e0d9] text-[9px] font-bold">{String(i + 1).padStart(2, '0')}</span><h3 className="text-sm font-bold md:text-base">{service}</h3>{tags[i].map(tag => <span key={tag} className="rounded-full border border-stone-200 bg-stone-50 px-2 py-1 text-[8px] font-bold tracking-wide text-stone-500">{tag}</span>)}</div>)}</div><div className="relative min-h-52 overflow-hidden rounded-2xl"><img className="absolute inset-0 h-full w-full object-cover" src="/assets/57a23.png" alt="Wellness support" /><span className="absolute bottom-3 right-3 rounded-full bg-white/90 px-3 py-1 text-[10px] font-bold">Empower holistic living</span></div></div></section>; }

function Transformation() { const left = ['I feel focused', 'I feel calmer', 'I feel balanced', 'I feel recharge', 'I feel energized', 'I feel more energized']; const right = ['I feel inspired', 'I feel powerful', 'I feel positive', 'I feel focus', 'I feel more in control', 'I feel purposeful']; return <section className="overflow-hidden bg-[linear-gradient(135deg,#5b3002,#8b520a,#5b3002)] px-6 py-24 text-white"><div className="mx-auto max-w-6xl text-center"><span className="rounded-full bg-white px-3 py-2 text-[10px] font-bold tracking-[0.12em] text-stone-900">A HEALTHIER TOMORROW</span><h2 className="mt-5 font-serif text-5xl leading-none">A healthier tomorrow starts today</h2><div className="mt-14 grid gap-12 text-left md:grid-cols-2"><div><p className="mb-4 font-serif text-lg">Flow for Life</p><div className="grid gap-3">{left.map(item => <span key={item} className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#3c210b]">＋ {item}</span>)}</div></div><div><p className="mb-4 font-serif text-lg">Flow for Growth</p><div className="grid gap-3">{right.map(item => <span key={item} className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#3c210b]">＋ {item}</span>)}</div></div></div><a href="#newsletter" className="mt-12 inline-block"><Pill light>Join Parna Today</Pill></a></div></section>; }

function Stories() { return <section className="mx-auto max-w-6xl px-6 py-24"><span className="rounded-full bg-[#d7dfe5] px-3 py-2 text-[10px] font-bold tracking-[0.12em]">CLIENT JOURNEY</span><h2 className="mt-5 border-b border-stone-200 pb-8 font-serif text-5xl leading-none">Real stories of growth, healing, and lasting change</h2><article className="mt-10 grid overflow-hidden rounded-3xl bg-[#f5efe7] shadow-[0_16px_0_#e2c3a3] md:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-[360px]"><img className="absolute inset-0 h-full w-full object-cover" src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1000&q=85" alt="Client video thumbnail" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-6 text-white"><span className="rounded-full bg-white/20 px-3 py-1 text-[10px] font-bold">Watch on YouTube</span><p className="mt-3 text-xs">A story of strength, recovery, and self-trust.</p><span className="mt-3 inline-block text-[10px] font-bold">5:00 MIN</span></div><span className="absolute left-1/2 top-1/2 grid h-14 w-14 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-red-600 text-xl text-white">▶</span></div><div className="p-8 md:p-12"><span className="rounded-full bg-white px-3 py-2 text-[10px] font-bold">STRESS & ANXIETY</span><h3 className="mt-6 font-serif text-4xl leading-none">A Journey from stress to serenity</h3><p className="mt-5 text-sm leading-relaxed text-stone-600">A personalized recovery plan helped create healthier routines, better sleep, and a renewed sense of emotional well-being.</p><div className="mt-6 flex items-center gap-3"><img className="h-10 w-10 rounded-full object-cover" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80" alt="Nilam Smith" /><div><p className="text-sm font-bold">Nilam Smith</p><a className="text-sm underline" href="#programs">View Details →</a></div></div><ul className="mt-7 grid gap-3 border-t border-stone-200 pt-6 text-sm text-stone-700"><li>✓ Experience deeper, more restorative sleep every night.</li><li>✓ Build healthier habits for a calmer, balanced life.</li></ul></div></article></section>; }

function Programs() { const programs = [['Depression & Anxiety', 'Rebuilding safe baseline states to gently pull you out of chronic shutdown or high-activation tension.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=85'], ['PTSD & Trauma Recovery', 'Restoring a secure boundary system so you can exist safely in the present moment.', 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=85'], ['Grief & Relationship Issue', 'Expanding your window of tolerance to hold profound loss with care.', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&q=85']]; return <section id="programs" className="mx-auto max-w-7xl px-6 py-24"><div className="text-center"><h2 className="mt-5 font-serif text-5xl">Lorem ipsum</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{programs.map(([title, copy, image]) => <article key={title} className="overflow-hidden rounded-2xl border border-stone-200 bg-[#fff9f0]"><img className="h-52 w-full object-cover" src={image} alt="" /><div className="p-6"><h3 className="font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-relaxed text-stone-600">{copy}</p></div></article>)}</div></section>; }

function Footer() { const groups = [['Platform', ['Our Story', 'What We Offer', 'Find a Practitioner']], ['Resources', ['Our Blog', 'Wellness Guides', 'In Press']], ['Legal', ['Privacy Policy', 'Terms of Service', 'Cookie Policy']], ['About', ['Our Method', 'Support Team', 'Contact']]]; return <footer id="newsletter" className="bg-[linear-gradient(135deg,#5b3002,#8b520a,#5b3002)] px-6 py-16 text-[#eadfd7]"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-7 border-b border-white/20 pb-12 md:flex-row md:items-center"><h2 className="max-w-xl text-4xl font-medium">Join our newsletter to get insights and updates</h2><form className="flex max-w-md flex-1 rounded-full border border-white/20 bg-white/10 p-2"><input className="min-w-0 flex-1 bg-transparent px-4 outline-none placeholder:text-white/50" placeholder="Email address" /><button className="rounded-full bg-white px-5 py-3 text-sm font-bold text-stone-900">Subscribe</button></form></div><div className="grid gap-8 py-10 md:grid-cols-5"><div><a href="#home" className="font-serif text-4xl">Parna</a><p className="mt-5 max-w-xs text-sm leading-relaxed text-white/70">Providing licensed online therapy and mental health support tailored directly to your life.</p></div>{groups.map(([heading, links]) => <div key={heading}><h3 className="mb-3 font-bold">{heading}</h3>{links.map(link => <a key={link} className="block py-1 text-sm text-white/70" href="#home">{link}</a>)}</div>)}</div><div className="border-t border-white/20 pt-6 text-sm text-white/50">© 2026 Parna. All rights reserved.</div></div></footer>; }

export default function App() { return <main className="overflow-hidden bg-white text-stone-900"><Hero /><About /><HowItWorks /><Services /><Transformation /><Stories /><Programs /><Footer /></main>; }
